### PR TITLE
✨MySQL configuration

### PR DESCRIPTION
**Pull request by ShiriNmi1520**
I've added port configuration for both the source and destination since some environment doesn't use the default 3306 port and it might cause problems.
P.S: Might change to using the default 3306 port when no `SRC_PORT` and `DEST_PORT` are present.

### CODE REVIEW

**Comment by ShiriNmi1520** [comment]
@kevinsmith If you think this change is suitable for this project, please consider merging it or you can give me some options to optimize/improve it. :smiling_face_with_tear:

**Comment by kevinsmith** [comment]
This looks good, @ShiriNmi1520, thank you!

> P.S: Might change to using the default 3306 port when no SRC_PORT and DEST_PORT are present.

Yes, I'd like to see it use 3306 by default if a port is not provided.

**Comment by ShiriNmi1520** [comment]
> This looks good, @ShiriNmi1520, thank you!
> 
> > P.S: Might change to using the default 3306 port when no SRC_PORT and DEST_PORT are present.
> 
> Yes, I'd like to see it use 3306 by default if a port is not provided.

Thanks for your replay, I'll add the default port later today 😃

**Comment by ShiriNmi1520** [comment]
@kevinsmith I've added default value for port argument 😃

**Comment by kevinsmith** [comment]
Thank you, @ShiriNmi1520!

**Pull request merged**
